version: '3.8'

networks:
  otel-network:
    external: true

services:
  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - 9464:9464
      - 4317:4317
      - 4318:4318
    networks:
      - otel-network

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: jaeger
    ports:
      - 16686:16686
    networks:
      - otel-network
    depends_on:
      - collector

  proxy:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./nginx/opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    networks:
      - otel-network

  apps:
    container_name: apps
    build:
      context: ./apps
      dockerfile: Dockerfile
    volumes:
      - ./apps:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    networks:
      - otel-network
    command: npm run start
    depends_on:
      - proxy
    ports:
      - 8090:8090
      - 8091:8091

  backend:
    build: ./backend
    container_name: backend
    image: backend-with-otel
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318/
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=backend
    networks:
      - otel-network